name: Windows build
on: [push]
jobs:
  stack:
    name: Build with stack
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Cache stack directories'
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~\AppData\Roaming\stack\pantry
          ~\AppData\Local\Programs\stack\pantry
          ~\AppData\Roaming\stack\snapshots
          ~\AppData\Local\Programs\stack\snapshots
          ~\AppData\Roaming\stack\stack.sqlite3
          ~\AppData\Local\Programs\stack\stack.sqlite3
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        save-always: true
    - name: Set up Haskell
      uses: haskell-actions/setup@v2.7.5
      with:
        ghc-version: '9.2'
        enable-stack: true
        stack-version: 'latest'
        stack-setup-ghc: true
    - name: 'stack setup'
      run: stack setup
    - name: 'Install dependencies'
      run: |
        cd C:\Users\runneradmin\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64
        ./bin/pacman -S mingw-w64-x86_64-libmariadbclient
    - name: 'Build with stack'
      run: 'stack build --no-terminal --lock-file error-on-write'
